# Generated by Django 3.1.1 on 2020-09-30 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('is_seasonal', models.BooleanField()),
                ('season_start', models.PositiveIntegerField(blank=True, null=True)),
                ('season_end', models.PositiveIntegerField(blank=True, null=True)),
                ('land_area_requirement', models.FloatField()),
                ('harvest_weight_per_land_area', models.FloatField()),
                ('harvest_time', models.PositiveIntegerField()),
                ('productivity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=14)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=14, verbose_name=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name=True)),
                ('land_area', models.FloatField(help_text="Farmer's land area in square meters")),
                ('is_available', models.BooleanField(help_text='Is the farmer able to take up orders?')),
            ],
            options={
                'ordering': ['location', 'name', '-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name=True)),
                ('weight', models.FloatField()),
                ('is_done', models.BooleanField(help_text='Is the order finished?')),
                ('is_cancelled', models.BooleanField(help_text='Is the order cancelled?')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.crop')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.customer')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Soil_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Pairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_time', models.DateTimeField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.farmer')),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login_register.order')),
            ],
            options={
                'ordering': ['-expected_time'],
            },
        ),
        migrations.CreateModel(
            name='Location_Soil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ManyToManyField(to='login_register.Location')),
                ('soil_type', models.ManyToManyField(to='login_register.Soil_type')),
            ],
            options={
                'verbose_name_plural': 'Location-Soil type Relations',
            },
        ),
        migrations.CreateModel(
            name='Location_Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ManyToManyField(to='login_register.Location')),
                ('name', models.ManyToManyField(to='login_register.Crop')),
            ],
            options={
                'verbose_name_plural': 'Location-Crop Relations',
            },
        ),
        migrations.AddField(
            model_name='farmer',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.location_soil'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.location_soil'),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Crop_Soil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ManyToManyField(to='login_register.Crop')),
                ('soil_type', models.ManyToManyField(to='login_register.Soil_type')),
            ],
            options={
                'verbose_name_plural': 'Crop-Soil type Relations',
            },
        ),
    ]
