# Generated by Django 3.1 on 2020-10-19 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('is_seasonal', models.BooleanField()),
                ('season_start', models.CharField(blank=True, choices=[('January', 1), ('Febuary', 2), ('March', 3), ('April', 4), ('May', 5), ('June', 6), ('July', 7), ('August', 8), ('September', 9), ('October', 10), ('November', 11), ('December', 12)], help_text='Start of the harvest season.', max_length=20, null=True)),
                ('season_end', models.CharField(blank=True, choices=[('January', 1), ('Febuary', 2), ('March', 3), ('April', 4), ('May', 5), ('June', 6), ('July', 7), ('August', 8), ('September', 9), ('October', 10), ('November', 11), ('December', 12)], help_text='End of the harvest seasons.', max_length=20, null=True)),
                ('harvest_weight_per_land_area', models.FloatField(help_text='Harvest weight per land area in tons/ha')),
                ('harvest_time', models.PositiveIntegerField(help_text='Harvest time in days')),
                ('productivity', models.FloatField(help_text='Arbitrary for now, set it later can be overriden.')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=14)),
                ('company', models.CharField(blank=True, max_length=30, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=14, verbose_name=True)),
                ('company', models.CharField(blank=True, max_length=30, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('land_area', models.FloatField(help_text="Farmer's land area in square meters", null=True)),
                ('is_available', models.BooleanField(help_text='Is the farmer able to take up orders?', null=True)),
            ],
            options={
                'ordering': ['location', 'name', '-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('street', models.CharField(default='', max_length=100)),
                ('brgy', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('province', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date in which the order was done', verbose_name='Order date')),
                ('weight', models.FloatField()),
                ('land_area_needed', models.FloatField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False, help_text='Is the order finished?')),
                ('is_reserved', models.BooleanField(default=False, help_text='Is  the order reserved?')),
                ('is_approved', models.BooleanField(default=False, help_text='Is the order approved by AtoANI?')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Posted', 'Posted'), ('Ongoing', 'Ongoing'), ('Harvested', 'Harvested'), ('Collected', 'Collected')], default='Pending', max_length=20, null=True)),
                ('message', models.CharField(blank=True, help_text='Cancellation Message', max_length=1000, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.crop')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.customer')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_register.location')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Soil_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
            ],
            options={
                'verbose_name_plural': 'Soil Types',
            },
        ),
        migrations.CreateModel(
            name='Order_Pairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_time', models.DateTimeField(blank=True, null=True)),
                ('accepted_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('harvested_date', models.DateTimeField(blank=True, null=True)),
                ('collected_date', models.DateTimeField(blank=True, help_text='To be filled up by AtoAni', null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.farmer')),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login_register.order')),
            ],
            options={
                'verbose_name_plural': 'Order Pairings',
                'ordering': ['-expected_time'],
            },
        ),
        migrations.CreateModel(
            name='Location_Soil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_register.location')),
                ('soil_type', models.ManyToManyField(to='login_register.Soil_type')),
            ],
            options={
                'verbose_name_plural': 'Location-Soil type Relations',
            },
        ),
        migrations.CreateModel(
            name='Location_Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_register.location')),
                ('name', models.ManyToManyField(help_text='Crop name', to='login_register.Crop')),
            ],
            options={
                'verbose_name_plural': 'Location-Crop Relations',
            },
        ),
        migrations.AddField(
            model_name='farmer',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.location'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.ManyToManyField(to='login_register.Location'),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Crop_Soil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(help_text='Crop name', null=True, on_delete=django.db.models.deletion.CASCADE, to='login_register.crop')),
                ('soil_type', models.ManyToManyField(to='login_register.Soil_type')),
            ],
            options={
                'verbose_name_plural': 'Crop-Soil type Relations',
            },
        ),
    ]
