# Generated by Django 3.1 on 2020-10-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='street',
            field=models.CharField(blank=True, help_text='Street of Customer', max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='street',
            field=models.CharField(blank=True, help_text='Street of Farmer', max_length=220, null=True),
        ),
    ]
