# Generated by Django 3.1 on 2020-10-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='available_land_area',
            field=models.FloatField(blank=True, help_text='Available planting land of farmer', null=True),
        ),
    ]
