# Generated by Django 3.1.1 on 2020-10-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_farmer_available_land_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='contact_number',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name=True),
        ),
    ]
