# Generated by Django 3.1 on 2020-10-30 07:30

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_auto_20201030_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='street',
            field=models.CharField(blank=True, help_text='Street of Customer', max_length=220, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
