# Generated by Django 3.1 on 2020-10-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0003_auto_20201019_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_pairing',
            name='status',
            field=models.CharField(default='Ongoing', max_length=100),
        ),
    ]
