# Generated by Django 3.1 on 2020-10-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0003_auto_20201030_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='street',
            field=models.CharField(blank=True, help_text='Street of Customer', max_length=5000, null=True),
        ),
    ]
