# Generated by Django 3.1 on 2020-10-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0004_order_pairing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Posted', 'Posted'), ('Ongoing', 'Ongoing'), ('Harvested', 'Harvested'), ('Collected', 'Collected')], default='Posted', max_length=20, null=True),
        ),
    ]
