# Generated by Django 3.1 on 2020-10-01 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0004_auto_20201001_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_pairing',
            options={'ordering': ['-expected_time'], 'verbose_name_plural': 'Order Pairings'},
        ),
        migrations.AlterModelOptions(
            name='soil_type',
            options={'verbose_name_plural': 'Soil Types'},
        ),
        migrations.RemoveField(
            model_name='crop_soil',
            name='name',
        ),
        migrations.AddField(
            model_name='crop_soil',
            name='name',
            field=models.ForeignKey(help_text='Crop name', null=True, on_delete=django.db.models.deletion.CASCADE, to='login_register.crop'),
        ),
        migrations.RemoveField(
            model_name='location_crop',
            name='location',
        ),
        migrations.AddField(
            model_name='location_crop',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_register.location'),
        ),
        migrations.AlterField(
            model_name='location_crop',
            name='name',
            field=models.ManyToManyField(help_text='Crop name', to='login_register.Crop'),
        ),
        migrations.RemoveField(
            model_name='location_soil',
            name='location',
        ),
        migrations.AddField(
            model_name='location_soil',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_register.location'),
        ),
    ]
