# Generated by Django 3.1 on 2020-10-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0004_auto_20201030_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Combined name for location', max_length=220),
        ),
    ]
