# Generated by Django 3.1 on 2020-10-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0005_auto_20201030_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=220),
        ),
    ]
