# Generated by Django 3.1 on 2020-10-26 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0006_auto_20201021_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_crop',
            field=models.CharField(help_text='Uninitialized crop, after add a crop in db, please select appropriate crop in the selection above', max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='crop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_register.crop'),
        ),
    ]
