# Generated by Django 3.1.1 on 2020-10-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0006_auto_20201001_1733'),
        ('login_register', '0004_auto_20201001_1737'),
    ]

    operations = [
    ]
