# Generated by Django 3.1 on 2020-10-31 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0006_auto_20201030_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_date',
            field=models.DateTimeField(blank=True, help_text='Date in which order was cancelled, automatically generated', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_cancelled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
