# Generated by Django 3.1 on 2020-11-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0007_auto_20201031_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='brgy',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
