# Generated by Django 3.1 on 2020-10-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0007_auto_20201026_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_pairing',
            name='delivered_date',
            field=models.DateTimeField(blank=True, help_text='To be filled up by AtoAni', null=True),
        ),
    ]
