# Generated by Django 3.1.1 on 2020-10-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0005_auto_20201001_1058'),
        ('login_register', '0007_merge_20201001_1800'),
    ]

    operations = [
    ]
