# Generated by Django 3.1.1 on 2020-11-03 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0008_auto_20201101_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_crop',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_register.location'),
        ),
    ]
