# Generated by Django 3.1.1 on 2020-10-01 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0008_merge_20201001_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='land_area',
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmer',
            name='company',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='brgy',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='province',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='street',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.location'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.location'),
        ),
    ]
