# Generated by Django 3.1 on 2020-11-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0008_auto_20201101_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approved_date',
            field=models.DateTimeField(blank=True, help_text='Date in which order was approved, automatically generated', null=True),
        ),
    ]
