# Generated by Django 3.1 on 2020-10-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0008_order_pairing_delivered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='first_question_answers',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='second_question_answers',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='first_question_answers',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='second_question_answers',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
