# Generated by Django 3.1 on 2020-11-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0009_order_approved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_pairing',
            name='status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
