# Generated by Django 3.1 on 2020-10-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0009_auto_20201027_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='contact_number',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Contact Number'),
        ),
    ]
