# Generated by Django 3.1 on 2020-10-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0010_auto_20201027_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='custom_crop',
            field=models.CharField(blank=True, help_text='Uninitialized crop, after add a crop in db, please select appropriate crop in the selection above', max_length=220, null=True),
        ),
    ]
