# Generated by Django 3.1 on 2020-11-05 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0009_auto_20201104_1950'),
        ('login_register', '0010_auto_20201103_0452'),
    ]

    operations = [
    ]
