# Generated by Django 3.1 on 2020-10-02 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0011_auto_20201002_0727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
    ]
