# Generated by Django 3.1 on 2020-11-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0012_auto_20201105_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location_soil',
            name='location',
        ),
        migrations.RemoveField(
            model_name='location_soil',
            name='soil_type',
        ),
        migrations.AlterField(
            model_name='location_crop',
            name='name',
            field=models.ManyToManyField(help_text='Crop name', null=True, to='login_register.Crop'),
        ),
        migrations.DeleteModel(
            name='Crop_Soil',
        ),
        migrations.DeleteModel(
            name='Location_Soil',
        ),
        migrations.DeleteModel(
            name='Soil_type',
        ),
    ]
