# Generated by Django 3.1 on 2020-10-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0012_auto_20201002_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='is_available',
            field=models.BooleanField(help_text='Is the farmer able to take up orders?', null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='land_area',
            field=models.FloatField(help_text="Farmer's land area in square meters", null=True),
        ),
    ]
