# Generated by Django 3.1 on 2020-11-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0013_auto_20201105_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_crop',
            name='name',
            field=models.ManyToManyField(help_text='Crop name', to='login_register.Crop'),
        ),
    ]
