# Generated by Django 3.1 on 2020-10-02 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0013_auto_20201002_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='crop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login_register.crop'),
        ),
    ]
