# Generated by Django 3.1 on 2020-10-02 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0014_auto_20201002_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_pairing',
            name='farmer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login_register.farmer'),
        ),
    ]
