# Generated by Django 3.1 on 2020-10-03 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0009_auto_20201001_1937'),
        ('login_register', '0015_auto_20201002_0851'),
    ]

    operations = [
    ]
