# Generated by Django 3.1 on 2020-10-03 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0016_merge_20201003_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_pairing',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.farmer'),
        ),
    ]
