# Generated by Django 3.1 on 2020-10-03 02:09

from django.db import migrations, models
import login_register.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0018_auto_20201003_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='land_area_requirement',
        ),
        migrations.AlterField(
            model_name='crop',
            name='harvest_time',
            field=models.PositiveIntegerField(help_text='Harvest time in days'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='harvest_weight_per_land_area',
            field=models.FloatField(help_text='Harvest weight per land area in tons/ha'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='productivity',
            field=models.FloatField(help_text='Arbitrary for now, set it later can be overriden.'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='season_end',
            field=models.CharField(blank=True, choices=[(login_register.models.Months['January'], 1), (login_register.models.Months['Febuary'], 2), (login_register.models.Months['March'], 3), (login_register.models.Months['April'], 4), (login_register.models.Months['May'], 5), (login_register.models.Months['June'], 6), (login_register.models.Months['July'], 7), (login_register.models.Months['August'], 8), (login_register.models.Months['September'], 9), (login_register.models.Months['October'], 10), (login_register.models.Months['November'], 11), (login_register.models.Months['December'], 12)], help_text='End of the harvest seasons.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='season_start',
            field=models.CharField(blank=True, choices=[(login_register.models.Months['January'], 1), (login_register.models.Months['Febuary'], 2), (login_register.models.Months['March'], 3), (login_register.models.Months['April'], 4), (login_register.models.Months['May'], 5), (login_register.models.Months['June'], 6), (login_register.models.Months['July'], 7), (login_register.models.Months['August'], 8), (login_register.models.Months['September'], 9), (login_register.models.Months['October'], 10), (login_register.models.Months['November'], 11), (login_register.models.Months['December'], 12)], help_text='Start of the harvest season.', max_length=20, null=True),
        ),
    ]
