# Generated by Django 3.1 on 2020-10-06 09:28

from django.db import migrations, models
import login_register.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0019_auto_20201003_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='season_end',
            field=models.CharField(blank=True, choices=[(1, login_register.models.Months['January']), (2, login_register.models.Months['Febuary']), (3, login_register.models.Months['March']), (4, login_register.models.Months['April']), (5, login_register.models.Months['May']), (6, login_register.models.Months['June']), (7, login_register.models.Months['July']), (8, login_register.models.Months['August']), (9, login_register.models.Months['September']), (10, login_register.models.Months['October']), (11, login_register.models.Months['November']), (12, login_register.models.Months['December'])], help_text='End of the harvest seasons.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='season_start',
            field=models.CharField(blank=True, choices=[(1, login_register.models.Months['January']), (2, login_register.models.Months['Febuary']), (3, login_register.models.Months['March']), (4, login_register.models.Months['April']), (5, login_register.models.Months['May']), (6, login_register.models.Months['June']), (7, login_register.models.Months['July']), (8, login_register.models.Months['August']), (9, login_register.models.Months['September']), (10, login_register.models.Months['October']), (11, login_register.models.Months['November']), (12, login_register.models.Months['December'])], help_text='Start of the harvest season.', max_length=20, null=True),
        ),
    ]
