# Generated by Django 3.1 on 2020-10-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0020_auto_20201006_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='season_end',
            field=models.CharField(blank=True, choices=[('January', 1), ('Febuary', 2), ('March', 3), ('April', 4), ('May', 5), ('June', 6), ('July', 7), ('August', 8), ('September', 9), ('October', 10), ('November', 11), ('December', 12)], help_text='End of the harvest seasons.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='season_start',
            field=models.CharField(blank=True, choices=[('January', 1), ('Febuary', 2), ('March', 3), ('April', 4), ('May', 5), ('June', 6), ('July', 7), ('August', 8), ('September', 9), ('October', 10), ('November', 11), ('December', 12)], help_text='Start of the harvest season.', max_length=20, null=True),
        ),
    ]
