# Generated by Django 3.1 on 2020-10-06 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0022_auto_20201006_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.crop'),
        ),
        migrations.AlterField(
            model_name='order_pairing',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login_register.order'),
        ),
    ]
