# Generated by Django 3.1 on 2020-10-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0023_auto_20201006_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.CharField(blank=True, help_text='Cancellation Message', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='order_pairing',
            name='accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_pairing',
            name='collected_date',
            field=models.DateTimeField(blank=True, help_text='To be filled up by AtoAni', null=True),
        ),
        migrations.AddField(
            model_name='order_pairing',
            name='harvested_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
