# Generated by Django 3.1 on 2020-10-07 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0024_auto_20201006_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 8, 42, 34, 558620), null=True, verbose_name=True),
        ),
    ]
