# Generated by Django 3.1 on 2020-10-07 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0027_auto_20201007_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date in which the order was done', verbose_name='Order date'),
        ),
    ]
