# Generated by Django 3.1.1 on 2020-10-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0028_auto_20201007_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_cancelled',
        ),
        migrations.AddField(
            model_name='order',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Is the order approved by AtoANI?'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_reserved',
            field=models.BooleanField(default=False, help_text='Is the order reserved?'),
        ),
    ]
