# Generated by Django 3.1 on 2020-10-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0028_auto_20201007_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='land_area_needed',
            field=models.FloatField(null=True),
        ),
    ]
