# Generated by Django 3.1.1 on 2020-10-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0029_auto_20201008_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_done',
            field=models.BooleanField(default=False, help_text='Is the order finished?'),
        ),
    ]
