# Generated by Django 3.1 on 2020-10-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0029_order_land_area_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Posted', 'Posted'), ('Ongoing', 'Ongoing'), ('Harvested', 'Harvested'), ('Collected', 'Collected')], default='Pending', max_length=20, null=True),
        ),
    ]
