# Generated by Django 3.1 on 2020-10-09 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0030_order_status'),
        ('login_register', '0030_auto_20201008_2154'),
    ]

    operations = [
    ]
