# Generated by Django 3.1 on 2020-10-09 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0031_merge_20201009_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_pairing',
            name='accepted_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 9, 9, 11, 29, 362750, tzinfo=utc), null=True),
        ),
    ]
