# Generated by Django 3.1 on 2020-10-09 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0032_auto_20201009_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_pairing',
            name='accepted_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
