# Generated by Django 3.1 on 2020-10-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0034_order_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='land_area_needed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
