# Generated by Django 3.1 on 2020-10-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0035_auto_20201010_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.ManyToManyField(to='login_register.Location'),
        ),
    ]
