# Generated by Django 3.1.2 on 2020-10-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0036_auto_20201016_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_reserved',
            field=models.BooleanField(default=False, help_text='Is  the order reserved?'),
        ),
    ]
